version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: fepa_postgres
    restart: always
    environment:
      POSTGRES_USER: fepa
      POSTGRES_PASSWORD: fepa123
      POSTGRES_DB: fepadatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
